### ISSUE TITLE
Disable  Available-spaces Feature When No Internet Connection is Available

### ISSUE THREAD

**Issue by iGotty** [ISIS3510-202410-Team-12/Flutter#113]
## Description
Currently, the application allows users to attempt finding rooms even when there is no active internet connection. This often leads to a poor user experience as the functionality depends on network availability to fetch room details.

## Expected Behavior
The room finding feature should be disabled or provide a clear message when the device is not connected to the internet. This would prevent the app from performing tasks that are known to fail under such conditions, thereby improving user experience.

## Possible Solution
Implement a check for internet connectivity before enabling the room finding functionality. If no connection is detected, disable the feature or notify the user with an appropriate message.

**Comment by SnowArtz** [comment]
It was done at #114
