### ISSUE TITLE
[Flutter] Implement the functionality for displaying locally saved events in case there is no internet connection.

### ISSUE THREAD

**Issue by jsurrea** [ISIS3510-202410-Team-12/Flutter#66]
Extend the functionality of the repository to query data from Local Storage when there is no internet connection. Sync the data with the server when internet is re-established.

**Comment by jsurrea** [comment]
Partially implemented by #99 : Currently showing local events only when there is no internet connection. When there is, local events get overwritten. We're missing a sync operation

**Comment by SnowArtz** [comment]
Already Implemented in #73
