### ISSUE TITLE
[Flutter] Implement the function that, in case there is no internet connection, the locally saved Groups and Friends should be displayed. (Eventual Connectivity)

### ISSUE THREAD

**Issue by SnowArtz** [ISIS3510-202410-Team-12/Flutter#70]
Implement the function that, in case there is no internet connection, the locally saved Groups and Friends should be displayed. (Eventual Connectivity)

**Comment by jsurrea** [comment]
Partially implemented by #99 : Currently showing events, groups and friends saved locally. We're missing the implementation of specific views for empty content vs connectivity error to let the user know why data is not rendering

**Comment by iGotty** [comment]
Completed at #104
