### ISSUE TITLE
[Flutter] Sync Locally Saved Groups with Backend on Internet Restoration

### ISSUE THREAD

**Issue by iGotty** [ISIS3510-202410-Team-12/Flutter#74]
Create a feature to automatically sync groups saved locally during offline modes with the backend upon regaining internet connectivity. This ensures data integrity and enhances user experience in fluctuating network conditions.

**Comment by jsurrea** [comment]
Partially implemented by #99 : Currently synchronizing local storage when internet connection is established (replacing data from backend into local storage). We are missing the implementation to push local changes into the backend.
