### ISSUE TITLE
NavBar not showing correct location after using sidebar

### ISSUE THREAD

**Issue by jsurrea** [ISIS3510-202410-Team-12/Flutter#91]
Check the following behavior when using the sidebar menu within the groups page!

https://github.com/ISIS3510-202410-Team-13/Flutter/assets/68788933/bbb6ca5c-f430-484a-beea-68b29bde255d

**Comment by iGotty** [comment]
The routes that are currently linked to the sidebar buttons were initially just for testing. In the future, they will perform the appropriate context.go for the view, which, according to our Figma design, will not have a navbar! @jsurrea

**Comment by jsurrea** [comment]
Thanks for letting me know! I will close the issue then 😃
